### ISSUE TITLE
"Could not find player config" Error

### ISSUE THREAD

**Issue by mightytyphoon** [appit-online/ionic-youtube-streams#2]
Hi, I am getting a "could not find player config" error on iOS (on a real device)

Any idea ?

**Comment by vappsProjects** [comment]
I have the same problem, you have found a solution?

**Comment by mightytyphoon** [comment]
@VictorVH6 sadly no, I used something else but it's not working with all videos, so for now this project (which is more a hobby project) is paused. As youtube changes a lot to avoid this kind of packages, it's hard to keep up with the changes and it should be a  paid job imo

**Comment by appit-online** [comment]
@mightytyphoon @vappsProjects please test the newest version 1.1.5 and verify that you have added the following plugin: cordova-plugin-advanced-http
