### ISSUE TITLE
ytApi return {"reload":"now"}

### ISSUE THREAD

**Issue by fjms** [appit-online/ionic-youtube-streams#3]
When the call "function searchVideo(youtubeId)" to the youtube url is parsed it gives an error because youtube does not return what is expected, return  {"reload":"now"}

**Comment by vappsProjects** [comment]
I get the following problem: "Could not find player config", do you know any solution?

**Comment by appit-online** [comment]
@fjms @vappsProjects please test the newest version 1.1.5
